//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.6.1055.0.
// 

namespace Grouping
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ReportData
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Country", IsNullable = false)]
        public List<ReportDataCountry> Data = new List<ReportDataCountry>();

        /// <remarks/>
        public ReportDataReferences References;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ReportDataCountry
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Region")]
        public List<ReportDataCountryRegion> Region = new List<ReportDataCountryRegion>();

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ReportDataCountryRegion
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Company")]
        public List<ReportDataCountryRegionCompany> Company = new List<ReportDataCountryRegionCompany>();

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ReportDataCountryRegionCompany
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sale")]
        public List<ReportDataCountryRegionCompanySale> Sale = new List<ReportDataCountryRegionCompanySale>();

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte companyId;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ReportDataCountryRegionCompanySale
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte productId;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contract;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime date;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint sum;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ReportDataReferences
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Company", IsNullable = false)]
        public List<ReportDataReferencesCompany> Companies = new List<ReportDataReferencesCompany>();

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Product", IsNullable = false)]
        public List<ReportDataReferencesProduct> Products = new List<ReportDataReferencesProduct>();
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ReportDataReferencesCompany
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ReportDataReferencesProduct
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
}